### ISSUE TITLE
!classic ability - broken with latest version

### ISSUE THREAD

**Issue by boktai1000** [mikeStr8s/ClassicBot#13]
**Describe the bug**
Previously, `!ability` would allow you to query and post abilities. Has this functionality been temporarily removed, or is this an issue as right now `!classic ability *ability name*` doesn't return anything

**To Reproduce**
`!classic ability Heroic Strike`

`!classic ability Blessing of Sacrifice`

**Expected behavior**
Should return a tooltip of the ability

**Screenshots**

Previously:

![image](https://user-images.githubusercontent.com/9054563/57249223-035e3400-700a-11e9-977b-f5601de3e5e6.png)

Currently:
![image](https://user-images.githubusercontent.com/9054563/57249247-0fe28c80-700a-11e9-9a35-660cdf40c6dd.png)

**Additional context**
I'm assuming you probably already know this, just clarifying if this was intended to be removed or not.

**Comment by mikeStr8s** [comment]
Intentionally removed for the time being so I can put my effort into making each piece of the bot close to 100% sound before extending further searching. !ability in its original state was so hit or miss with the way it was able to be parsed that I opted to remove it in order to focus on one piece at a time. I will get to re-adding support for the ability search when I believe item searching is in a stable position.

Thank you for your continued interest and keeping my intentions transparent for users! Keep up the good work.

**Comment by mikeStr8s** [comment]
I believe this issue is a quick fix, while testing with my existing parser and search functionality when typing `!classic spell heroic strike` the bot returns:

![image](https://user-images.githubusercontent.com/10874994/57400764-3affe400-71a2-11e9-9750-00ce19949374.png)

Which is accurate as far as spell tooltips go. I am glad I had the forethought to attempt to make a modular parsing system. I will continue to test and then begin implementation of this into the main system as there was no modifications to core parsing to implement.

**Comment by mikeStr8s** [comment]
Added in dev. Further tweaking on the image rendering required, but functionally should be there.
