### ISSUE TITLE
Classic Bot has been offline since yesterday. 

### ISSUE THREAD

**Issue by Kaitology** [mikeStr8s/ClassicBot#15]
**Describe the bug**
Bot has been offline since yesterday 10pm CEST time. (About 20 hours ago at writing of this post.)

**To Reproduce**
N/A

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mikeStr8s** [comment]
Hello! Firstly, I want to apologize for my absense on the issue and my absense as a developer on this project.

Second, in response to your actual issue @Kaitology, I am aware. As mentioned above I have been absent and the IRL matters that I have been attending to might have thrown my home server offline. I hope that this has not been detrimental to your opinion of the bot, or myself as the developer.

I am working on getting my home server back up and running. Fingers crossed I can do just that within the next 5ish hours (sadly a little more complex than plugging it back in).

I want to continue to thank you for your support at helping me make this a good as it can be. I have made a discord server so that you can get in direct contact with me easier and in a more timely manner. Please consider joining, its still in development so its pretty empty ATM. 

https://discord.gg/PDmsnu4

**Comment by mikeStr8s** [comment]
The bot has been moved to a cloud service. Should no longer be offline due to IRL reason now and in the future.
