### ISSUE TITLE
Issues with different items that have duplicate names

### ISSUE THREAD

**Issue by boktai1000** [mikeStr8s/ClassicBot#5]
As of right now, there seems to be an issue with items that have multiple versions but the same name. ClassicBot does seem to report one of them, but I am not currently aware of a way to specify different variants or how those edge cases would be handled.

An example of this is for "Atiesh, Greatstaff of the Guardian" which has a variant for each class capable of using it.

Would maybe having an additional argument after your item be able to handle this, I believe this would also require being able to support quotes then or accommodating these edge cases.

Example:

`item! "Atiesh, Greatstaff of the Guardian" priest`

**Comment by mikeStr8s** [comment]
@boktai1000 thank you for your continued feedback. This is something that I want to get into the search as soon as possible. I am currently trying to tie up any loose ends in my development version of the bot with the search/parser overhaul. While I do not believe that this request will make it into my initial release, I do want to make sure that its understood that even these edge cases are important to me in order to make this work the best it can.

This has been tagged as an enhancement because although you are not getting the item you wanted, the bot is behaving as expected. I would love for this issue to act as a discussion board for how to best implement arguments into a search command with the main goal of making it have the least user impact as possible. Please continue to comment with ideas and supporting arguments and I will be sure to reply to each one in turn with my thoughts.

**Comment by mikeStr8s** [comment]
This is still under investigation. Due to the tactics I use to gather the metadata and parse into an image, it looks as though I cannot alter the results I receive based on the criteria above.

There are a couple more methods that I am going to be looking into in order to make this work.

**Comment by mikeStr8s** [comment]
I have come to the conclusion that without a direct image of the wow item database for the bot to use directly, this is no longer within scope of the project. I am sorry, but with the limited endpoints and data that is query-able out there, this is not possible from my vantage point.
