### ISSUE TITLE
Bot replies twice, readme incorrect data

### ISSUE THREAD

**Issue by Kaitology** [mikeStr8s/ClassicBot#9]
!classic item/abillity does not work. The old commands !ability and !item still work and it replies twice. 

![image](https://user-images.githubusercontent.com/50146411/57157205-56ed3980-6de0-11e9-8c82-2ba93ab136bc.png)

Issue #3 was closed for unknown reason, partial matching still does not work. In fact it doesn't work at all anymore:
![image](https://user-images.githubusercontent.com/50146411/57157350-c06d4800-6de0-11e9-89fc-391f01d6e686.png)

See image.

**Comment by mikeStr8s** [comment]
Hello, I am sorry for the confusion. Right now the github instance of the bot is updated to the newest version v0.3.0

The server hosting the bot is currently still on v0.2.5 as I am currently unable to interract with the server to update. This issue is completely my fault, and I should have waited to update versioning until I could.

> !classic item/abillity does not work. The old commands !ability and !item still work

You are absolutely correct, for the reasons mentioned above, as of writing this reply, the server the bot is hosted on is still on v0.2.5. `!item` and `!ability` are both going to be the only way to use the bot for about another 1-2 hours until I have access to my server.

> Issue #3 was closed for unknown reason, partial matching still does not work. In fact it doesn't work at all anymore:

Again, you are absolutely correct. I will spare you from reading the same thing for a third time. I am sure you understand why it is the way it is.

Please have patience with me, this was definitely a fumble on my end. I should not have jumped the gun and updated the master branch without having access to my server to update the bot as well. I will leave this issue open until I get the newest version up and running. I am sorry for the inconveniece and I am sorry to have been the exact opposite of transparent.

**Comment by mikeStr8s** [comment]
The server has successfully been updated. Thank you for your patience. The README should now be an accurate representation of the status of the bot that is live.
